### ISSUE TITLE
Additional Gestures

### ISSUE THREAD

**Issue by lukeirvin** [santa112358/story#44]
Is there a way to modify the overall gesture controls so we can add our own gestures?

For example, what if I want to make a story with an image that can link to a website?

**Comment by santa112358** [comment]
Hi @lukeirvin 

Have you tried this method? 
https://pub.dev/documentation/story/latest/story_page_view_story_page_view/StoryPageView/gestureItemBuilder.html

**Comment by lukeirvin** [comment]
@santa112358 Yes. I've been able to resolve this, for the most part. I'll close this issue out & open a new issue.
