### ISSUE TITLE
Option to start viewing stories from any story

### ISSUE THREAD

**Issue by tatoline** [santa112358/story#7]
I couldn't find any option to start in the middle. Let's say there are 10 users' stories, what if end user doesn't press the first story, and instead press second story? It should be start on second story but end user also should view first story without going back and clicking the first story; they should do that by the same way like going to previous story. Is there an option to do that? Maybe I just missed that

**Comment by santa112358** [comment]
Hi @tatoline, you can specify the initial index by adding the value to [initialPage](https://pub.dev/documentation/story/latest/story_page_view_story_page_view/StoryPageView/initialPage.html). This argument is not written on readme, so maybe I have to update it.

Thank you.
