### ISSUE TITLE
onPageLimitReached Double pop()

### ISSUE THREAD

**Issue by tatoline** [santa112358/story#8]
If there is `pop()` on `onPageLimitReached`, when the last story is finish, it closes normally as expected. But if end user tap the right side to the last story (like try to go to next story), pop() method is called twice and users find themselves on a page they don't want.

`StoryPageView(
   onPageLimitReached: () {
          Navigator.pop(context);
        }
)`

**Comment by santa112358** [comment]
@tatoline  
Updated version to 0.3.0 and fixed this problem🎉
Thank you for the report!
https://pub.dev/packages/story
